// src/app/layout.tsx
import type { Metadata } from "next";
import "./globals.css";
import { editorial, Surtifont } from "@/lib/font";
import Nav from "@/app/_navigation/Nav";
import Footer from "@/app/_navigation/Footer";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className={`${editorial.variable} ${Surtifont.variable}`}>
        <body className={`${editorial.className} ${Surtifont.className} text-primary`} >
        <Nav  />
            {children}
        <Footer />
        </body>
        </html>
    );
}


