// src/app/layout.tsx
import type { Metadata } from "next";
import "./globals.css";
import { Aylafont, Geistfont } from "@/lib/font";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className={`${Aylafont.variable} ${Geistfont.variable}`}>
        <body className={`${Aylafont.className} ${Geistfont.className}`}>{children}</body>
        </html>
    );
}